apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitbucket-pvc
  namespace: nima-bitbucket
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2
