apiVersion: v1
kind: Service
metadata:
  name: bitbucket
  namespace: nima-bitbucket
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: |
      Environment=Development,Owner=agangulappa@altimetrik.com,Project=Development,Application=Chatbot
spec:
  ports:
    - port: 31180
      targetPort: 7990
  selector:
    app: bitbucket
  type: LoadBalancer

